---
- name: Create local logs directory
  file:
    path: "{{ playbook_dir }}/../logs"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Create local reports directory
  file:
    path: "{{ playbook_dir }}/../reports"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Create server-specific log directory
  file:
    path: "{{ playbook_dir }}/../logs/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Check Apache status
  shell: systemctl is-active apache2
  register: apache_status
  when: "'webservers' in group_names"
  changed_when: false
  ignore_errors: yes

- name: Check MySQL status
  shell: systemctl is-active mysql
  register: mysql_status
  when: "'databases' in group_names"
  changed_when: false
  ignore_errors: yes

- name: Check if PM2 is running
  shell: which pm2
  register: pm2_check
  when: "'sveltekit' in group_names"
  changed_when: false
  ignore_errors: yes

- name: Check SvelteKit status
  shell: |
    if [ -f /home/ubuntu/.pm2/logs/sveltekit-out.log ]; then
      echo "active"
    else
      echo "inactive"
    fi
  register: sveltekit_status
  when: "'sveltekit' in group_names"
  changed_when: false
  ignore_errors: yes

- name: Check Node Exporter status
  shell: systemctl is-active node_exporter
  register: node_exporter_status
  changed_when: false
  ignore_errors: yes

- name: Fetch web server logs
  fetch:
    src: /var/log/apache2/access.log
    dest: "{{ playbook_dir }}/../logs/{{ inventory_hostname }}/"
    flat: yes
  when: "'webservers' in group_names"
  ignore_errors: yes

- name: Fetch database logs
  fetch:
    src: /var/log/mysql/error.log
    dest: "{{ playbook_dir }}/../logs/{{ inventory_hostname }}/"
    flat: yes
  when: "'databases' in group_names"
  ignore_errors: yes

- name: Get SvelteKit PM2 logs
  shell: |
    if [ -f /home/ubuntu/.pm2/logs/sveltekit-out.log ]; then
      tail -n 100 /home/ubuntu/.pm2/logs/sveltekit-out.log > /tmp/sveltekit.log
    else
      echo "No SvelteKit logs found" > /tmp/sveltekit.log
    fi
  when: "'sveltekit' in group_names"
  ignore_errors: yes

- name: Fetch SvelteKit logs
  fetch:
    src: /tmp/sveltekit.log
    dest: "{{ playbook_dir }}/../logs/{{ inventory_hostname }}/"
    flat: yes
  when: "'sveltekit' in group_names"
  ignore_errors: yes

- name: Clean up temporary SvelteKit log
  file:
    path: /tmp/sveltekit.log
    state: absent
  when: "'sveltekit' in group_names"
  ignore_errors: yes

- name: Generate deployment report
  template:
    src: deployment_report.j2
    dest: "{{ playbook_dir }}/../reports/deployment_report_{{ ansible_date_time.iso8601_basic_short }}.txt"
    mode: '0644'
  delegate_to: localhost
  run_once: true 