---
# Install MySQL
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

# Start and enable MySQL service
- name: Start and enable MySQL service
  systemd:
    name: mysql
    state: started
    enabled: yes

# Set MySQL root password and privileges
- name: Set MySQL root password and privileges
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    state: present
  when: mysql_root_password is defined

# Create event_manager database
- name: Create event_manager database
  mysql_db:
    name: event_manager
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Create MySQL user for event_manager
- name: Create MySQL user for event_manager
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: 'event_manager.*:ALL'
    host: '%'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_user is defined and mysql_password is defined

# Copy init.sql to remote server
- name: Copy init.sql to remote server
  copy:
    src: init.sql
    dest: /tmp/init.sql
    mode: '0644'

# Run init.sql
- name: Check if tables exist
  mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    database: event_manager
    query: "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'event_manager'"
  register: table_check

- name: Run init.sql
  mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    database: event_manager
    query: "{{ lookup('file', '/tmp/init.sql') }}"
  when: table_check.query_result[0][0] == 0 