---
# Install required packages
- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

# Ensure DNS resolution works
- name: Install DNS utilities
  apt:
    name: 
      - dnsutils
      - resolvconf
    state: present
    update_cache: yes

- name: Configure DNS servers
  copy:
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    dest: /etc/resolv.conf
    mode: '0644'
  become: true

- name: Create application directory
  file:
    path: /var/www/sveltekit
    state: directory
    mode: '0755'

# Check if repository exists and is up to date
- name: Check if repository exists
  stat:
    path: /var/www/sveltekit/.git
  register: repo_check

- name: Clone the repository
  git:
    repo: "{{ sveltekit_repo_url }}"
    dest: /var/www/sveltekit
    version: "{{ sveltekit_repo_branch }}"
    force: yes
  register: git_clone

- name: Install dependencies
  npm:
    path: /var/www/sveltekit
    state: present

- name: Build the application
  npm:
    path: /var/www/sveltekit
    run: build
  when: git_clone.changed

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Create ecosystem.config.js
  copy:
    content: |
      module.exports = {
        apps: [{
          name: 'event-manager',
          cwd: '/var/www/sveltekit',
          script: 'npm',
          args: 'run preview -- --host 0.0.0.0 --port 3000',
          env: {
            NODE_ENV: 'production',
            PORT: 3000
          }
        }]
      }
    dest: /var/www/sveltekit/ecosystem.config.js
    mode: '0644'

- name: Stop existing PM2 process if running
  shell: pm2 delete all || true
  ignore_errors: yes

- name: Start the application with PM2
  shell: |
    cd /var/www/sveltekit
    pm2 start ecosystem.config.js

- name: Save PM2 process list
  shell: pm2 save

- name: Setup PM2 to start on boot
  shell: pm2 startup
  become: true 