---
- name: Deploy Web Server
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: Deploy Database Server
  hosts: databases
  become: yes
  roles:
    - database

- name: Deploy SvelteKit Application
  hosts: sveltekit
  become: yes
  roles:
    - sveltekit

- name: Deploy Monitoring
  hosts: all
  become: yes
  roles:
    - monitoring

- name: Collect Logs and Generate Report
  hosts: all
  roles:
    - logging 